### ISSUE TITLE
breaks terminal on mac

### ISSUE THREAD

**Issue by purezen** [mklement0/n-install#5]
After installing n by following the 'curl ...' command in my home directory.. my shell is not starting.
It closes as soon as it starts. The behaviour is both on Terminal and iTerm2 apps.

I am using zsh btw.

**Comment by mklement0** [comment]
I am sorry to hear that.

All `n-install` is supposed to do is to add the equivalent of the following to `~/.zshrc`:

    [[ -f /Users/jdoe/n/bin/typex ]] && . /Users/jdoe/n/bin/typex # Added by typex -i; typex -u to remove.

Can you paste the contents of `~/.zshrc` here or send me a link to a copy?

If you have trouble getting to it, because Finder doesn't show it, use the following trick:

* Open `TextEdit.app`
* Bring up the open-a-file dialog with ⌘O
* Navigate to your home folder (⇧⌘H)
* Press ⇧⌘. (period) to make hidden items visible: at that point, you should see all `.*` files/folders, among them `.zshrc`.

From there you can also rename or delete the file, so that at least your Terminal should work again.

**Comment by mklement0** [comment]
Incidentally, the symptom you describe implies that the shell _terminates_ right away, in the process of sourcing its startup files, which can have two causes:

* a misplaced `exit` command: nothing in a startup file (profile / initialization file) or called via sourcing from it should ever execute `exit`, as that terminates the entire shell right away.

* the shell _crashes_

The line that `n-install` adds to `~/.zshrc` doesn't contain `exit`, and I couldn't think of why it would cause a crash.

**Comment by mklement0** [comment]
I'm closing this for now, until we have a better sense of what happened, but I'm happy to reopen if `n-install` turns out to be the culprit.
